### ISSUE TITLE
Feature Request: Authenticate via the API

### ISSUE THREAD

**Issue by petergillardmoss** [apiaxle/apiaxle#72]
Hello,

It would be nice to be able to authenticate directly via the API.

Architecturally this would separate the proxy from apiaxle allowing different modes of working.  

For example, applications could call the API directly from inside (without the need for a proxy) or proxy servers, such as nginx, could be used to front applications whilst delegating to apiaxle for authentication, limiting, monitoring etc. on the APIs.

Thanks
Peter

**Comment by fillup** [comment]
The original design was to reuse the authentication capabilities provided by the proxy rather than re-implement them directly in the API. Since the API itself does not require authentication you can put anything you want in front of it to perform that function so long as you keep it secure obviously.
